name = "altamed-c"
compatibility_date = "2025-05-30"

# Настройки для Next.js на Cloudflare Pages
compatibility_flags = ["nodejs_compat"]

# Переменные окружения
[vars]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# Настройки для Cloudflare Pages
[build]
command = "npm run build"
cwd = ""
watch_dir = "src"

# Настройки для продакшн окружения
[env.production]
name = "altamed-c"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1" 